services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    env_file: "db-config.env"
    ports:
      - 8080:80
    volumes:
      - "./web:/var/www/html:ro"
    networks:
      - app-network
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/db_password
    secrets:
      - db_password
secrets:
  db_password:
    file: db_password.txt

networks:
  app-network:
