services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    env_file:
      -path: "./db-config.env"
    ports:
      - 8080:80
    volumes:
      - "./web:/var/www/html:ro"
    networks:
      - app-network
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    env_file:
      -path: "./db-config.env"
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
networks:
  app-network:
